remote_theme: sylhare/Type-on-Strap

# THEME-SPECIFIC CONFIGURATION
title: My Blog                                   # site's title
description: "My blog to record my stuff"      # used by search engines

# Header and footer text
header_text: My Blog  # Change Blog header text
header_feature_image: assets/img/header/triangular.jpeg    # 2484 x 1280
header_feature_image_responsive: true
footer_text: >
  Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a>; Hosted on Github Pages

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                             # Enable if using math markup
mermaid: default                                        # Enable mermaid-js for diagrams, use theme: base, forest, dark, default, neutral
google_analytics:                                       # Tracking ID, e.g. "UA-000000-01"
cookie_consent: true                                    # To respect the usage of cookies
color_theme: auto                                       # auto, dark or light

# BLOG CONFIGURATION
post_navigation: true
paginate: 10
paginate_path: "blog/page:num"
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
